"use client";
import type { CandidateProfile } from "@/lib/schema";
import { artifactText, freshness, type FreshnessState, type Proposal } from "@/lib/freshness";

type Props = { profile: CandidateProfile; state: FreshnessState; artifactKey: string; proposal: Proposal | null; onKeep: () => void; onEdit: () => void; onPreview: () => void; onPreviewAi?: () => void; onAccept: () => void; onCancel: () => void };
export function WordingReview({ profile, state, artifactKey, proposal, onKeep, onEdit, onPreview, onPreviewAi, onAccept, onCancel }: Props) {
  const status = freshness(profile, state, artifactKey);
  const a = state.artifacts[artifactKey];
  const project = state.projects.indexOf(artifactKey);
  const experience = state.experience.indexOf(artifactKey);
  const sources = artifactKey === "summary" ? [profile.careerGoal.role, ...profile.education.map((e) => [e.degree, e.major, e.graduation].filter(Boolean).join(" · ")), ...profile.projects.map((p) => [p.name, p.built, p.contribution, p.technologies, p.outcome].filter(Boolean).join(" · ")), ...profile.experience.map((e) => [e.role, e.organization, e.dates, e.details].filter(Boolean).join(" · ")), ...Object.values(profile.skills), ...profile.volunteering, ...profile.training, ...profile.certifications, ...profile.awards] : project >= 0 ? Object.entries(profile.projects[project]).filter(([k]) => !["bullets", "link"].includes(k)).map(([k, v]) => `${({ name: "Project", problem: "Context", built: "Built", contribution: "Contribution", technologies: "Tools", outcome: "Result" } as Record<string, string>)[k]}: ${v}`) : experience >= 0 ? Object.entries(profile.experience[experience]).filter(([k]) => k !== "bullets").map(([k, v]) => `${({ role: "Role", organization: "Organization", dates: "Dates", details: "Action" } as Record<string, string>)[k]}: ${v}`) : [];
  return <section className="wording-review no-print" aria-label="Wording review">
    <p role="status"><strong>{status === "stale" ? "Details changed — review wording" : status === "unknown" ? "Freshness unknown" : a.event === "kept" ? "Kept after review" : "Current source revision"}</strong> · {a.origin === "manual" ? "Manually edited" : a.origin === "unknown" ? "Origin unknown" : a.origin === "groq" ? "AI wording" : "Guided wording"}{a.event === "regenerated" ? " · Rewrite accepted" : ""}</p>
    <p className="hint">{status === "stale" ? "These details changed after this wording was written. Your wording is preserved." : status === "unknown" ? "This saved wording has no recorded source revision. Review it against your facts." : "A matching revision records review history. It does not verify that a claim is true."}</p>
    <details open={status !== "current"}><summary>Compare current facts and wording</summary><div className="wording-comparison"><div><strong>Current facts</strong><ul>{sources.filter(Boolean).map((line, i) => <li key={i}>{line}</li>)}</ul></div><div><strong>Chosen wording</strong>{artifactText(profile, state, artifactKey).map((line, i) => <p key={i}>{line || "(empty line)"}</p>)}</div></div></details>
    <div className="wording-actions"><button className="text-button" type="button" onClick={onKeep}>Keep wording</button><button className="text-button" type="button" onClick={onEdit}>Edit manually</button><button className="text-button" type="button" onClick={onPreview}>Preview Guided rewrite</button>{onPreviewAi && <button className="text-button" type="button" onClick={onPreviewAi}>Preview AI rewrite</button>}</div><p className="hint">Keep acknowledges this revision for review; it is not external verification. Rewrites may omit details: compare before accepting.</p>
    {proposal && <div className="rewrite-proposal" role="region" aria-label="Guided rewrite proposal"><h3>Proposed replacement</h3><div className="wording-comparison"><div><strong>Before</strong>{proposal.before.map((line, i) => <p key={i}>{line || "(empty line)"}</p>)}</div><div><strong>After</strong>{proposal.after.length ? proposal.after.map((line, i) => <p key={i}>{line}</p>) : <p>No action supplied. Accepting will clear this wording.</p>}</div></div><div className="wording-actions"><button className="button primary" type="button" onClick={onAccept}>Accept replacement</button><button className="button secondary" type="button" onClick={onCancel}>Cancel replacement</button></div></div>}
  </section>;
}
